
spring.application.name=NatureLink

# Nom de l'application

# Configuration de la base de données MySQL

spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/naturelink?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

# Configuration Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.springframework=DEBUG

# Désactiver la session Hibernate dans la vue pour éviter les erreurs LazyInitializationException
spring.jpa.open-in-view=false

# Port du serveur Spring Boot
server.port=9000
>>>>>>> master
